### ISSUE TITLE
Can't compile project

### ISSUE THREAD

**Issue by Oppa-YA** [ChrisVega/Geiger-Counter-ATtiny85#1]
Hi, @ChrisVega . I tried different versions of Arduino IDE, but can't compile a project for OLED display. I always stuck at error "call of overloaded 'String(float&, int)' is ambiguous"
Can you help me please?

Here is full error code:
D:\Arduino\Giger_counter_v6_attiny_OLED\Giger_counter_v6_attiny_OLED.ino: In function 'void loop()':

Giger_counter_v6_attiny_OLED:48: error: call of overloaded 'String(float&, int)' is ambiguous

     DoseDis = String(Dose, 4);

                             ^

D:\Arduino\Giger_counter_v6_attiny_OLED\Giger_counter_v6_attiny_OLED.ino:48:29: note: candidates are:

In file included from C:\Users\shado\AppData\Local\Arduino15\packages\digistump\hardware\avr\1.6.7\cores\tiny/WProgram.h:17:0,

                 from C:\Users\shado\AppData\Local\Arduino15\packages\digistump\hardware\avr\1.6.7\cores\tiny/Arduino.h:4,

                 from sketch\Giger_counter_v6_attiny_OLED.ino.cpp:1:

C:\Users\shado\AppData\Local\Arduino15\packages\digistump\hardware\avr\1.6.7\cores\tiny/WString.h:39:5: note: String::String(long unsigned int, int)

     String( const unsigned long, const int base=10 );

     ^

C:\Users\shado\AppData\Local\Arduino15\packages\digistump\hardware\avr\1.6.7\cores\tiny/WString.h:38:5: note: String::String(long int, int)

     String( const long, const int base=10 );

     ^

C:\Users\shado\AppData\Local\Arduino15\packages\digistump\hardware\avr\1.6.7\cores\tiny/WString.h:37:5: note: String::String(unsigned int, int)

     String( const unsigned int, const int base=10 );

     ^

C:\Users\shado\AppData\Local\Arduino15\packages\digistump\hardware\avr\1.6.7\cores\tiny/WString.h:36:5: note: String::String(int, int)

     String( const int, const int base=10);

     ^

Giger_counter_v6_attiny_OLED:53: error: 'class String' has no member named 'c_str'

     SSD1306.ssd1306_string_font6x8(CPMdis.c_str());

                                           ^

Giger_counter_v6_attiny_OLED:55: error: 'class String' has no member named 'c_str'

     SSD1306.ssd1306_string_font6x8(DoseDis.c_str());

                                            ^

Multiple libraries were found for "font6x8.h"
 Used: C:\Users\shado\Documents\Arduino\libraries\ssd1306xled-master
 Not used: C:\Users\shado\AppData\Local\Arduino15\packages\digistump\hardware\avr\1.6.7\libraries\DigisparkOLED
 Not used: C:\Users\shado\AppData\Local\Arduino15\packages\digistump\hardware\avr\1.6.7\libraries\DigisparkOLED
 Not used: C:\Users\shado\AppData\Local\Arduino15\packages\digistump\hardware\avr\1.6.7\libraries\DigisparkOLED
 Not used: C:\Users\shado\AppData\Local\Arduino15\packages\digistump\hardware\avr\1.6.7\libraries\DigisparkOLED
exit status 1
call of overloaded 'String(float&, int)' is ambiguous

**Comment by ChrisVega** [comment]
The attiny core you are using has no constructor for a String class that
has float as it's parameter. If you're using the core I listed under LCD
that's why, it's a bit outdated outdated. The only reason I used it is because the LCD library for the attiny85 wouldn't work without it.

Use the core they use here and it should work.
https://www.hackster.io/arjun/programming-attiny85-with-arduino-uno-afb829

**Comment by Shadowern** [comment]
Thank you Chris for very fast response!
Now i get it, it's because i compiling project for tiny85 dev board with bootloader (i have digispark).
Never have problems before with it tiny project's, that's why i don't find a problem after day trying to run it. After your answer I changed Arduino settings and try compile it for generic tiny85 and it compile imidiately. Well, i'll will find clean cheep and try this later.
Thanks again!

**Comment by Oppa-YA** [comment]
Thank you Chris for very fast response!
Now i get it, it's because i compiling project for tiny85 dev board with bootloader (i have digispark).
Never have problems before with it tiny project's, that's why i don't find a problem after day trying to run it. After your answer I changed Arduino settings and try compile it for generic tiny85 and it compile imidiately. Well, i'll will find clean cheep and try this later.
Thanks again!

**Comment by ChrisVega** [comment]
No problem, I'm just glad someone is getting use out of my code. Good luck with your project.

**Comment by boxerjl2** [comment]
so is this not compatible with the digispark? ive been trying to figure it out myself for hours and then saw this issue and did what you said to do so that sketch would finally compile but i cant get it onto the digispark
